name: Release to pub.dev

on:
  release:
    types:
      - published

jobs:
  run-tests:
    uses: ./.github/workflows/ci.yml
  publish:
    needs: run-tests
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1







